django_project/blog/urls.py
from django.urls import path
from .views import (PostListView, PostDetailView, UserDetailView, PostCreateView, PostUpdateView, PostDeleteView,
                    ImagePostDetailView, ImagePostListView, ImagePostCreateView, ImagePostDeleteView,
                    ImagePostUpdateView,
                    VideoPostListView, VideoPostDeleteView, VideoPostCreateView, VideoPostDetailView,
                    VideoPostUpdateView,
                    UserPostListView, UserDeleteView, UserListView)
from . import views

# urls for {% url 'blog-home' %}
urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('create/', views.create_post, name='create'),
    path('about/', views.about, name='blog-about'),
    path('all_users/', UserListView.as_view(), name='blog-all_users'),
    path('user/posts/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/delete', UserDeleteView.as_view(), name='user-delete'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('image_posts/', ImagePostListView.as_view(), name='blog-home_images'),
    path('image_posts/<int:pk>/', ImagePostDetailView.as_view(), name='image_post-detail'),
    path('image_posts/new/', ImagePostCreateView.as_view(), name='image_post-create'),
    path('image_posts/<int:pk>/update', ImagePostUpdateView.as_view(), name='image_post-update'),
    path('image_posts/<int:pk>/delete', ImagePostDeleteView.as_view(), name='image_post-delete'),
    path('video_posts/', VideoPostListView.as_view(), name='blog-home_videos'),
    path('video_posts/<int:pk>/', VideoPostDetailView.as_view(), name='video_post-detail'),
    path('video_posts/new/', VideoPostCreateView.as_view(), name='video_post-create'),
    path('video_posts/<int:pk>/update', VideoPostUpdateView.as_view(), name='video_post-update'),
    path('video_posts/<int:pk>/delete', VideoPostDeleteView.as_view(), name='video_post-delete'),
]

django_project/django_project/urls.py
# if ..users, ImportError: attempted relative import beyond top-level package

# 2 logouts here because it's impossible to have logout url with LogoutView, since method for getting to url is always
#  'GET', and it's not allowed with LogoutView, but I still need it, so I made page for logout that uses form

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('logout-page/', user_views.logout_page, name='logout-page'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include('blog.urls')),
    path('profile/', user_views.profile, name='profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/blog/models.py
import os
from uuid import uuid4

from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.deconstruct import deconstructible
from PIL import Image


@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)


path_and_rename = PathAndRename("profile_pics")


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    # author = models.ForeignKey(User, on_delete=models.SET_NULL)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class ImagePost(models.Model):
    title = models.CharField(max_length=100)
    content = models.ImageField(upload_to=path_and_rename)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.content.path)

        if img.height > 1000 or img.width > 1000:
            output_size = (1000, 1000)
            img.thumbnail(output_size)
            img.save(self.content.path)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('image_post-detail', kwargs={'pk': self.pk})


class VideoPost(models.Model):
    title = models.CharField(max_length=100)
    content = models.FileField(upload_to=path_and_rename, null=True, validators=[FileExtensionValidator(
                                 allowed_extensions=['mp4'])])
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('video_post-detail', kwargs={'pk': self.pk})

django_project/users/models.py
import os
from uuid import uuid4
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import mark_safe
from PIL import Image

from django.utils.deconstruct import deconstructible


@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)


path_and_rename = PathAndRename("profile_pics")


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to=path_and_rename)
    bio = models.TextField(null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

django_project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.html import mark_safe
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bio']

django_project/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView, DetailView,
    CreateView, UpdateView, DeleteView)
from .models import Post, ImagePost, VideoPost


# Create your views here.


def home(request):
    context = {
        'posts': Post.objects.all(),
        'title': "Home page",
    }
    return render(request, template_name="blog/home.html", context=context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'   # <app>/<model>_<viewtype>.html    # blog/post_list.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 24


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog/post/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog/post/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = "/"
    template_name = 'blog/post/post_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class ImagePostListView(ListView):
    model = ImagePost
    template_name = 'blog/image_post/home-images.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 40


class ImagePostDetailView(DetailView):
    model = ImagePost
    template_name = 'blog/image_post/imagepost_detail.html'


class ImagePostCreateView(LoginRequiredMixin, CreateView):
    model = ImagePost
    fields = ['title', 'content']
    template_name = 'blog/image_post/imagepost_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ImagePostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ImagePost
    fields = ['title', 'content']
    template_name = 'blog/image_post/imagepost_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class ImagePostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = ImagePost
    success_url = "images_posts/"
    template_name = 'blog/image_post/imagepost_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class VideoPostListView(ListView):
    model = VideoPost
    template_name = 'blog/video_post/home-videos.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 40


class VideoPostDetailView(DetailView):
    model = VideoPost
    template_name = 'blog/video_post/videopost_detail.html'


class VideoPostCreateView(LoginRequiredMixin, CreateView):
    model = VideoPost
    fields = ['title', 'content']
    template_name = 'blog/video_post/videopost_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class VideoPostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = VideoPost
    fields = ['title', 'content']
    template_name = 'blog/video_post/videopost_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class VideoPostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = VideoPost
    success_url = "/"
    template_name = 'blog/video_post/videopost_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        else:
            return False


class UserDetailView(DetailView):
    model = User
    template_name = 'blog/user/user_detail.html'
    context_object_name = 'some_user'


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user/user_posts.html'   # <app>/<model>_<viewtype>.html    # blog/post_list.html
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    success_url = "/"
    template_name = "blog/user/user_confirm_delete.html"

    def test_func(self):
        user = self.get_object()
        if self.request.user == user:
            return True
        else:
            return False


class UserListView(ListView):
    model = User
    template_name = "blog/user/user_list.html"
    context_object_name = 'users'
    ordering = ['date_joined']
    paginate_by = 10


def about(request):
    return render(request, template_name="blog/about.html", context={'title': "About page"})


def create_post(request):
    return render(request, template_name="blog/create.html", context={"title": "Create Post"})

# not used anymore
#
# def all_users(request):
#     context = {
#         'users': User.objects.all(),
#         'title': 'All Users'
#     }
#     return render(request, template_name="blog/all_users.html", context=context)

django_project/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
# from .models import Profile


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            messages.success(request, f"Thanks for creating an account! You are now logged in.")
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'])
            login(request, new_user)
            return redirect('blog-home')
    else:
        form = UserRegisterForm()
    return render(request, template_name='users/register.html', context={'form': form})


@login_required
def logout_page(request):
    return render(request, template_name='users/logout-page.html', context={"title": "Logout"})


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, "Your account has been updated!")
            return redirect('profile')
        if p_form.is_valid():
            p_form.save()
            messages.success(request, "Your account has been updated!")
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'users/profile.html', context)

django_project/blog/templates/blog/user/user_confirm_delete.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="post">
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend class="border-bottom mb-4">Delete User</legend>
            <h2>Are you sure you want to delete your account, {{ object.username }}?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a href="{% url 'profile' %}" class="btn btn-outline-info" type="submit">Return to the Profile</a>
        </div>
    </form>
</div>
{% endblock body %}

django_project/blog/templates/blog/user/user_detail.html
{% extends 'blog/base.html' %}
{% block body %}
    <div class="post">
        <div class="content-section">
            <div class="media">
                <img class="rounded-circle account-img" src="{{ some_user.profile.image.url }}">
                <div class="media-body">
                    <h2 class="account-heading">{{ some_user.username }}</h2>
                    <p class="text-secondary">{{ some_user.email }}</p>
                    <p>{{ some_user.profile.bio|linebreaks }}</p>
                    {% if some_user == request.user %}
                    <a class="btn btn-outline-info" href="{% url 'profile' %}">Edit Profile</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="home-body">
        {% for i in object.post_set.all %}
            <div class="post-object">
                <a class="article-title" href="{% url 'post-detail' i.id %}"><h1 style="font-size: 12px;">
                    {{ i.title }} </h1></a>
                <small><img class="rounded-circle post-account-img" src="{{ i.author.profile.image.url }}">
                <a href="{% url 'user-detail' i.author.id %}">{{ i.author }}</a> - {{ i.date_posted|date:"F d, Y" }} </small><br><br>
                <a href="{% url 'post-detail' i.id %}" class="btn btn-outline-secondary">View Post</a>
            </div>
        {% endfor %}
        {% for i in object.imagepost_set.all %}
            <div class="home-image_post-object">
                <a class="article-title" href="{% url 'image_post-detail' i.id %}"><h1 style="font-size: 12px;">
                    {{ i.title }} </h1></a>
                <small><img class="rounded-circle post-account-img" src="{{ i.author.profile.image.url }}">
                <a href="{% url 'user-detail' i.author.id %}">{{ i.author }}</a> - {{ i.date_posted|date:"F d, Y" }} </small>
                <hr><br>
                <img class="home-posts-image" src="{{ i.content.url }}"> <br>
                <a href="{% url 'image_post-detail' i.id %}" class="btn btn-outline-secondary">View Post</a>
            </div>
        {% endfor %}
        {% for i in object.videopost_set.all %}
            <div class="home-image_post-object">
                <a class="article-title" href="{% url 'video_post-detail' i.id %}"><h1 style="font-size: 12px;">
                    {{ i.title }} </h1></a>
                <small><img class="rounded-circle post-account-img" src="{{ i.author.profile.image.url }}">
                <a href="{% url 'user-detail' i.author.id %}">{{ i.author }}</a> - {{ i.date_posted|date:"F d, Y" }} </small>
                <hr><br>
                <video class="home-posts-image" >
                    <source src="{{ i.content.url }}" type="video/mp4">
                </video><br>
                <a href="{% url 'video_post-detail' i.id %}" class="btn btn-outline-secondary">View Post</a>
            </div>
        {% endfor %}
<!--        pagination -->
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a class="btn btn-info" href="?page=1">1</a>
                {% if page_obj.previous_page_number > 1 %}
                    ...<a class="btn btn-info" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                {% endif %}
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num%}
                    <a class="btn btn-secondary" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-info" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                    ...<a class="btn btn-info" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>


{% endblock body %}

django_project/blog/templates/blog/user/user_list.html
{% extends 'blog/base.html' %}
{% block body %}
    {% for i in users %}
        <div class="post">
            <div class="content-section">
                <div class="media">
                    <img class="rounded-circle account-img" src="{{ i.profile.image.url }}">
                    <div class="media-body">
                        <a href="{% url 'user-detail' i.id %}"><h2 class="account-heading">{{ i.username }}</h2></a>
                        <p class="text-secondary">{{ i.email }}</p>
                        {% if i.profile.bio %}<p>{{ i.profile.bio|linebreaks }}</p>{% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-info" href="?page=1">1</a>
            {% if page_obj.previous_page_number > 1 %}
                ...<a class="btn btn-info" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num%}
                <a class="btn btn-secondary" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-info" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                ...<a class="btn btn-info" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock body %}

django_project/blog/templates/blog/user/user_posts.html
{% extends "blog/base.html" %}
{% block body %}
    <div class="post">
        <div class="content-section">
            <div class="media">
                <div class="media-body">
                    <h1 class="account-heading">{{ view.kwargs.username }}</h1>
                    <p class="text-secondary">{{ view.kwargs.email }}</p>
                    {% if view.kwargs.username == user.username %}
                        <a class="btn btn-outline-info" href="{% url 'profile' %}">Edit Profile</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% for i in posts %}
        <div class="post">
            <a class="article-title" href="{% url 'post-detail' i.id %}"><h1> {{ i.title }} </h1></a>
            <small><img class="rounded-circle post-account-img" src="{{ i.author.profile.image.url }}">
            <a href="{% url 'user-detail' i.author.id %}">{{ i.author }}</a> - {{ i.date_posted|date:"F d, Y" }} </small>  <hr>
            {% if i.content %}<h2>{{ i.content }} </h2>{% endif %}
        </div>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-info" href="?page=1">1</a>
            {% if page_obj.previous_page_number > 1 %}
                ...<a class="btn btn-info" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num%}
                <a class="btn btn-secondary" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-info" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            {% if page_obj.next_page_number < page_obj.paginator.num_pages %}
                ...<a class="btn btn-info" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
{% endif %}

{% endblock body %}